apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fg8z4fsx2-python
  janus-idp.io/tekton: fg8z4fsx2-python
  backstage.io/kubernetes-id: fg8z4fsx2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fg8z4fsx2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
